### ISSUE TITLE
db: name of service not known

### ISSUE THREAD

**Issue by psychoAB** [Go-In/go-coup#144]
![image](https://user-images.githubusercontent.com/16674480/32982200-0f470a86-ccb3-11e7-958d-44de08ff3d32.png)

**Comment by monthol8th** [comment]
เดี๋ยวดูให้ครับ

**Comment by monthol8th** [comment]
เจอล่ะ ปัญหามันมาจากการเปลี่ยน docker image ของ db จาก postgres:latest มาใช้ postgres:alpine อ่ะ ที่เปลี่ยนเพราะกะจะลดแรม+แก้ปัญหา backward comp.
วิธีแก้ก็
```bash
docker-compose rm db
docker-compose build db
```
