### ISSUE TITLE
หน้า ticket แสดงชื่อ username ของ store

### ISSUE THREAD

**Issue by psychoAB** [Go-In/go-coup#150]
มันควรจะเป็น storename มากกว่าไหม?

![image](https://user-images.githubusercontent.com/16674480/33068077-bfaf5f5a-cee2-11e7-99a1-c7ebccaa77d5.png)

**Comment by RocKIn0X** [comment]
มันชื่อคูปองหนิ

**Comment by monthol8th** [comment]
หมายถึงตรงคำว่า kfc ตรงฝั่งซ้ายรึเปล่าหว่า?

**Comment by psychoAB** [comment]
kfc บน exp date อะ
