### ISSUE TITLE
Validate หน้า add-edit ticket

### ISSUE THREAD

**Issue by monthol8th** [Go-In/go-coup#154]
![screen shot 2017-11-22 at 8 25 20 am](https://user-images.githubusercontent.com/22114870/33105225-bd67805c-cf5e-11e7-90d2-d7d62129ba27.png)

* ติ๊ก is period แล้วไม่ใส่ remaining day(จน.วันที่สามารถใช้ได้) ได้
* ติ๊ก is limit แล้วไม่ใส่ remaining(จำนวนตั๋วที่จำหน่าย) ได้
* Price ใส่เกินinteger limit แล้วบรึ้ม _อาจต้องแก้ที่ models เอา_

**Comment by seaiin** [comment]
จะให้ใส่ limit ของ price, remaining day, remaining เท่าไร

**Comment by monthol8th** [comment]
2 พันล้าน
