### ISSUE TITLE
ตัว generate code ของ coupon

### ISSUE THREAD

**Issue by RocKIn0X** [Go-In/go-coup#158]
เอาตัว coupon เข้ารหัส เพื่อความ secure ตอน store จะสแกน qr code ของ coupon

**Comment by monthol8th** [comment]
ฝากเช็ค #159 ด้วยว่าเหมือนกับที่ require ไปรึเปล่า?

**Comment by RocKIn0X** [comment]
โอเค เหมือนๆ
