### ISSUE TITLE
ส่ง data ผ่าน button ยังไง

### ISSUE THREAD

**Issue by RocKIn0X** [Go-In/go-coup#168]
![image](https://user-images.githubusercontent.com/15122086/33218838-a5287810-d171-11e7-94f3-c7a28f8b8b85.png)
ไม่รู้ว่าจะส่งตัว coupon_url ไปให้ modal ยังไง

**Comment by monthol8th** [comment]
เรื่องแนวๆนี้ต้องถาม @komcal หรือ @tidjungs เอาอ่ะ 555

แต่วิธีการที่ง่ายที่สุดคือการ bind data เท่ากับ button แล้วไปจัดการ data ที่ onclick เอา

**Comment by komkanit** [comment]
ตอบใน #173 แล้ว
