### ISSUE TITLE
ส่ง string ไปที่ modal-body ยังไง

### ISSUE THREAD

**Issue by RocKIn0X** [Go-In/go-coup#173]
![image](https://user-images.githubusercontent.com/15122086/33241197-96220334-d2f4-11e7-9892-e745628e8296.png)

**Comment by komkanit** [comment]
https://github.com/Go-In/go-coup/blob/1a1c61707a2d6546aad6e63c303f0712d2e7f07e/web/templates/index/coupon.html#L45

สามารถดึง url จาก attribute ได้
